
services:
  fine_tune_llm:
    build: ./
    container_name: fine_tune_llm
    ports:
      - "8888:8888"
    volumes:
      - ./:/workspace
      - ~/.cache:/root/.cache 
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    
    working_dir: /workspace
    ipc: host 
    
    ulimits:  
      memlock: -1
      stack: 67108864

    dns:
      - 8.8.8.8  
      - 8.8.4.4
    
    restart: unless-stopped 